services:
  blazorcrud_proyecto01:
    image: ${DOCKER_REGISTRY-}blazorcrudproyecto01
    build:
      context: .
      dockerfile: BlazorCrud_Proyecto01/Dockerfile
    ports:
      - "8003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BlazorCrudDB;User Id=sa;Password=MiClaveSegura!123;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MiClaveSegura!123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: