FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:3fcf6f1e809c0553f9feb222369f58749af314af6f063f389cbd2f913b4ad556 AS build
WORKDIR /src

COPY ["BlazorCrud_Proyecto01/BlazorCrud_Proyecto01.csproj", "BlazorCrud_Proyecto01/"]
RUN dotnet restore "BlazorCrud_Proyecto01/BlazorCrud_Proyecto01.csproj"

COPY . ./BlazorCrud_Proyecto01
WORKDIR "/src/BlazorCrud_Proyecto01"
RUN dotnet build "BlazorCrud_Proyecto01.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BlazorCrud_Proyecto01.csproj" -c Release -o /app/publish /p:UseAppHost=false
#RUN dotnet publish "BlazorCrud_Proyecto01.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0@sha256:b4bea3a52a0a77317fa93c5bbdb076623f81e3e2f201078d89914da71318b5d8 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BlazorCrud_Proyecto01.dll"]



# Build runtime image
#FROM mcr.microsoft.com/dotnet/aspnet:9.0@sha256:b4bea3a52a0a77317fa93c5bbdb076623f81e3e2f201078d89914da71318b5d8
#WORKDIR /App
#COPY --from=build /App/out .
#ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]
#